export const elementTypes = [
  { type: 'container', label: 'Container', icon: '📦', category: 'Layout' },
  { type: 'div', label: 'Div', icon: '□', category: 'Layout' },
  { type: 'grid', label: 'Grid', icon: '⊞', category: 'Layout' },
  { type: 'h1', label: 'Heading 1', icon: 'H1', category: 'Text' },
  { type: 'h2', label: 'Heading 2', icon: 'H2', category: 'Text' },
  { type: 'h3', label: 'Heading 3', icon: 'H3', category: 'Text' },
  { type: 'h4', label: 'Heading 4', icon: 'H4', category: 'Text' },
  { type: 'h5', label: 'Heading 5', icon: 'H5', category: 'Text' },
  { type: 'h6', label: 'Heading 6', icon: 'H6', category: 'Text' },
  { type: 'p', label: 'Paragraph', icon: 'P', category: 'Text' },
  { type: 'span', label: 'Span', icon: 'S', category: 'Text' },
  { type: 'strong', label: 'Bold', icon: 'B', category: 'Text' },
  { type: 'em', label: 'Italic', icon: 'I', category: 'Text' },
  { type: 'small', label: 'Small', icon: 's', category: 'Text' },
  { type: 'button', label: 'Button', icon: '🔘', category: 'Interactive' },
  { type: 'a', label: 'Link', icon: '🔗', category: 'Interactive' },
  { type: 'form', label: 'Form', icon: '📝', category: 'Interactive' },
  { type: 'input', label: 'Input', icon: '📥', category: 'Interactive' },
  { type: 'textarea', label: 'Textarea', icon: '📄', category: 'Interactive' },
  { type: 'select', label: 'Select', icon: '▼', category: 'Interactive' },
  { type: 'option', label: 'Option', icon: '◦', category: 'Interactive' },
  { type: 'label', label: 'Label', icon: '🏷️', category: 'Interactive' },
  { type: 'img', label: 'Image', icon: '🖼️', category: 'Media' },
  { type: 'video', label: 'Video', icon: '🎬', category: 'Media' },
  { type: 'audio', label: 'Audio', icon: '🎵', category: 'Media' },
  { type: 'iframe', label: 'iFrame', icon: '🌐', category: 'Media' },
  { type: 'ul', label: 'List (ul)', icon: '•', category: 'Lists' },
  { type: 'ol', label: 'List (ol)', icon: '1.', category: 'Lists' },
  { type: 'li', label: 'List Item', icon: '◦', category: 'Lists' },
  { type: 'br', label: 'Line Break', icon: '↵', category: 'Utility' },
  { type: 'hr', label: 'Divider', icon: '─', category: 'Utility' },
];

export const categories = ['Layout', 'Text', 'Interactive', 'Media', 'Lists', 'Utility'];
